import './health.ts'
import './organisation.ts'
import './activites.ts'
import './identite.ts'
import './installation.ts'
import './personnes.ts'
import './taches.ts'
import './commentaires.ts'
import './fiches.ts'
import './recherche.ts'
import './notifications.ts'
import './push.ts'
import './score.ts'
import './postes.ts'
import './souhaits.ts'
import './demandes.ts'
import './formulaire.ts'
import './messages.ts'
import './flux.ts'
import './notes-de-version.ts'

import { builder } from './builder.ts'

export const schema = builder.toSchema()
