-- AlterTable
ALTER TABLE `Notification` ADD COLUMN `ficheId` VARCHAR(191) NULL,
    ADD COLUMN `statut` ENUM('A_FAIRE', 'EN_COURS', 'FAITE', 'ABANDONNEE') NULL,
    MODIFY `type` ENUM('TACHE_CREEE', 'TACHE_MODIFIEE', 'TACHE_ASSIGNEE', 'TACHE_DESASSIGNEE', 'ECHEANCE_PROCHE', 'TACHE_EN_RETARD', 'DEMANDE_RECUE', 'TACHE_STATUT', 'FICHE_CREEE', 'FICHE_MODIFIEE') NOT NULL;

-- AlterTable
ALTER TABLE `PreferenceNotification` ADD COLUMN `applicationPerimetre` BOOLEAN NOT NULL DEFAULT true;

-- AddForeignKey
ALTER TABLE `Notification` ADD CONSTRAINT `Notification_ficheId_fkey` FOREIGN KEY (`ficheId`) REFERENCES `Fiche`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
